language: php

php: 
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - FRAMEWORK_VERSION="4.0.*" SKELETON_VERSION="4.0.*"
  - FRAMEWORK_VERSION="4.1.*" SKELETON_VERSION="4.1.*"
  - FRAMEWORK_VERSION="4.2.*" SKELETON_VERSION="4.2.*"

before_script:
  - composer self-update
  - composer require laravel/framework:${FRAMEWORK_VERSION} --no-update
  - composer require laravel/laravel:${SKELETON_VERSION} --dev --no-update
  - composer install --dev --prefer-dist

script: phpunit
